### ISSUE TITLE
Gak bisa discan untuk MD

### ISSUE THREAD

**Issue by primahagantha** [Aiinne/Aine-MD#1]
Udah berkali kali dicoba tetap gak bisa discan.

**Comment by Aiinne** [comment]
Pakai panel atau rdp bisa di scan atau mau chat ke WhatsApp saya
wa.me/62895330379186 nnti saya bantu scan

**Comment by primahagantha** [comment]
Server di pterodatcyl btw

**Comment by techwiz37** [comment]
faktor face jd gbsa scan
