### ISSUE TITLE
No support Ubuntu 

### ISSUE THREAD

**Issue by VendingMp** [Aiinne/Aine-MD#10]
Hello Can Fix its, me run bot in Ubuntu server and get error
yarn no support to run in Ubuntu

**Comment by hdiiofficial** [comment]
> Hello Can Fix its, me run bot in Ubuntu server and get error yarn no support to run in Ubuntu

sudo apt update 
sudo apt install git 
sudo apt install nodejs 
sudo apt install ffmpeg 
sudo apt install imagemagick 
git clone https://github.com/Aiinne/Aine-MD
cd Aine-MD
npm install
node .


Try this cmd.

**Comment by VendingMp** [comment]
Fix. I install on RDP and get node_modules
