### ISSUE TITLE
TOLONG KERJA SAMA NYA..

### ISSUE THREAD

**Issue by Aiinne** [Aiinne/Aine-MD#14]
Tolong jangan di jual Script ini..
Saya capek coding kalian para kontol pada ngejual script,
Ngotak kontol, Emang kalian kira ngefix script tinggal bimsalambim?

Saya ga akan update script publik ini, jika butuh update silahkan hubungi
WhatsApp saya..
Biar ketauan para kontol yang ngejual script gratisan..
Nanti saya kasih script update nya

**Comment by Hansalrl** [comment]
blacklist aja bang,btw ikut projectnya dong mwehehe sekalian belajar handler**:v**

**Comment by Nonhoman4** [comment]
Ikut muntung ada yang mau 🗿👍

**Comment by akmallxx** [comment]
saran ya min, mendng dibikin console.log trus kasi kontakmu, jan lupa di enc, jid klo dijual kan ketauan sm yg beli

**Comment by Aiinne** [comment]
![Screenshot_2022-06-25-18-07-40-940_com whatsapp](https://user-images.githubusercontent.com/79745902/175770936-359077b3-7240-425e-82ae-61ad0173cd58.jpg)
Inilah orang yg jual SC 
Identitas nya
github.com/xzeebotz
wa.me/6281381685954

**Comment by Hansalrl** [comment]
minta dianu kak

**Comment by Hansalrl** [comment]
> Ikut muntung ada yang mau🗿👍

boleh😀🗿

**Comment by Pojan16** [comment]
> Tolong jangan di jual Script ini.. Saya capek coding kalian para kontol pada ngejual script, Ngotak kontol, Emang kalian kira ngefix script tinggal bimsalambim?
> 
> Saya ga akan update script publik ini, jika butuh update silahkan hubungi WhatsApp saya.. Biar ketauan para kontol yang ngejual script gratisan.. Nanti saya kasih script update nya

izin fork sama kode ulang kak, sumber aman, gada buy sell😁👌

**Comment by Levi576** [comment]
> 

Ga peduli deck 🗿
